spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: \[Spring Cloud Gateway Global Filter\]
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true